backend:
  name: git-gateway
  branch: netlify
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

site_url: https://coroncino.netlify.app

media_folder: static/img
public_folder: /img

slug: 
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "mainimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}]}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/products/index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
  - name: "vini"
    label: "Vino"
    folder: "src/cms/vini"
    create: true
    identifier_field: wineName
    slug: "{{wineName}}"
    fields:
      - label: "Nome del vino"
        widget: "string"
        name: "wineName"
      - label: "Descrizione"
        name: "wineDescription"
        widget: "markdown"
      - label: "Immagine principale"
        name: "mainImage"
        widget: "image"
      - label: "Da che vigneto/i viene?"
        name: "vigneti"
        widget: "relation"
        collection: "vigneti"
        required: false
        multiple: true
        valueField: "nomeVigneto"
        searchFields: ["nomeVigneto", "body"]
        displayFields: ["nomeVigneto", "body"] 
      - label: "Ha vinto premi? Aggiungili qui"
        name: "premi"
        widget: "relation"
        collection: "premi"
        required: false
        multiple: true
        valueField: "nomePremio"
        searchFields: ["nomePremio", "annoPremio"]
        displayFields: ["nomePremio", "annoPremio"] 

  - name: "vigneti"
    label: "Vigneto"
    identifier_field: nomeVigneto
    slug: "{{nomeVigneto}}"
    folder: "src/cms/vigneti"
    create: true
    fields:
      - label: "Nome vigneto"
        widget: "string"
        name: "nomeVigneto"
      - label: "Descrizione"
        name: "body"
        widget: "markdown"
      - label: "Immagine principale"
        name: "mainImage"
        widget: "image"

  - name: "premi"
    label: "Premio"
    identifier_field: nomePremio
    slug: "{{nomePremio}}-{{annoPremio}}"
    folder: "src/cms/vigneti"
    create: true
    sortable_fields: ['nomePremio', 'annoPremio']
    fields:
      - label: "Nome del premio"
        widget: "string"
        name: "nomePremio"
      - label: "Anno del premio"
        widget: "string"
        name: "annoPremio"
      - label: "Descrizione"
        name: "body"
        widget: "markdown"
      - label: "Immagine principale"
        name: "mainImage"
        widget: "image"
      - label: "Quale vino ha vinto? Aggiungi qui"
        name: "vino"
        widget: "relation"
        collection: "vini"
        required: true
        valueField: "nomeVino"
        searchFields: ["nomeVino", "annoVino"]
        displayFields: ["nomeVino", "annoVino"] 
      - label: "Annata del vino che ha vinto"
        widget: "string"
        name: "annoVinoPremiato"
