locale: 'it'

backend:
  name: git-gateway
  branch: netlify
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

site_url: https://coroncino.netlify.app

media_folder: static/img
public_folder: /img

slug: 
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "mainimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
  - name: "pages"
    label: "Pagine (inglese)"
    files:
      - file: "src/pages/wines/index.en.md"
        label: "Pagina Vini Inglese"
        name: "wines"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "wines-page"}
          - {label: Titolo, name: title, widget: string}
          - {label: Descrizione, name: description, widget: string}
  - name: "pagine"
    label: "Pagine"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}]}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/products/index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
      - file: "src/pages/vini/index.it.md"
        label: "Pagina Vini"
        name: "wines"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "wines-page"}
          - {label: Titolo, name: title, widget: string}
          - {label: Descrizione, name: description, widget: string}
  - name: "vini"
    label: "Vino"
    extension: it.md
    format: frontmatter
    folder: "src/cms/wines"
    create: true
    identifier_field: wineName
    slug: "{{wineName}}"
    fields:
      - label: "Nome del vino"
        widget: "string"
        name: "wineName"
      - label: "Descrizione"
        name: "wineDescription"
        widget: "markdown"
      - label: "Foto"
        required: false
        name: "images"
        widget: "list"
        summary: '{{fields.image}}'
        field: {label: Foto, name: image, widget: image}
      - label: "Da che vigneto/i viene?"
        name: "vineyards"
        widget: "relation"
        collection: "vigneti"
        required: false
        multiple: true
        valueField: "vineyard"
        searchFields: ["vineyard", "body"]
        displayFields: ["vineyard", "body"] 
      # - label: "Ha vinto premi? Aggiungili qui"
      #   name: "prizes"
      #   widget: "relation"
      #   collection: "prizes"
      #   required: false
      #   multiple: true
      #   valueField: "prize"
      #   searchFields: ["prize", "annoPremio"]
      #   displayFields: ["prize", "annoPremio"] 
  - name: "wines"
    label: "Vino (inglese)"
    extension: en.md
    format: frontmatter
    folder: "src/cms/wines/en"
    create: true
    identifier_field: wineName
    slug: "{{wineName}}"
    fields:
      - label: "Nome del vino"
        widget: "string"
        name: "wineName"
      - label: "Descrizione"
        name: "wineDescription"
        widget: "markdown"
      - label: "Foto"
        required: false
        name: "images"
        widget: "list"
        summary: '{{fields.image}}'
        field: {label: Foto, name: image, widget: image}
      - label: "Da che vigneto/i viene?"
        name: "vineyards"
        widget: "relation"
        collection: "vineyards"
        required: false
        multiple: true
        valueField: "vineyard"
        searchFields: ["vineyard", "body"]
        displayFields: ["vineyard", "body"] 
      # - label: "Ha vinto premi? Aggiungili qui"
      #   name: "prizes"
      #   widget: "relation"
      #   collection: "prizes"
      #   required: false
      #   multiple: true
      #   valueField: "prize"
      #   searchFields: ["prize", "annoPremio"]
      #   displayFields: ["prize", "annoPremio"] 

  - name: "vigneti"
    label: "Vigneto"
    extension: it.md
    format: frontmatter
    identifier_field: vineyard
    slug: "{{vineyard}}"
    folder: "src/cms/vineyards"
    create: true
    fields:
      - label: "Nome vigneto"
        widget: "string"
        name: "vineyard"
      - label: "lang"
        name: "lang"
        widget: "hidden"
        default: "it"
      - label: "Descrizione"
        name: "body"
        widget: "markdown"
      - label: "Foto"
        required: false
        name: "images"
        widget: "list"
        summary: '{{fields.image}}'
        field: {label: Foto, name: image, widget: image}
  - name: "vineyards"
    label: "Vigneto"
    extension: en.md
    format: frontmatter
    identifier_field: vineyard
    slug: "{{vineyard}}"
    folder: "src/cms/vineyards/en"
    create: true
    fields:
      - label: "Nome vigneto"
        widget: "string"
        name: "vineyard"
      - label: "lang"
        name: "lang"
        widget: "hidden"
        default: "en"
      - label: "Descrizione"
        name: "body"
        widget: "markdown"
      - label: "Foto"
        required: false
        name: "images"
        widget: "list"
        summary: '{{fields.image}}'
        field: {label: Foto, name: image, widget: image}

  - name: "premi"
    label: "Premi"
    extension: it.md
    format: frontmatter
    identifier_field: prize
    slug: "{{prize}}-{{annoPremio}}"
    folder: "src/cms/prizes"
    create: true
    sortable_fields: ['prize', 'annoPremio']
    fields:
      - label: "Nome del premio"
        widget: "string"
        name: "prize"
      - label: "lang"
        name: "lang"
        widget: "hidden"
        default: "it"
      - label: "Anno del premio"
        widget: "string"
        name: "annoPremio"
      - label: "Descrizione"
        name: "body"
        widget: "markdown"
      - label: "Foto"
        required: false
        name: "images"
        widget: "list"
        summary: '{{fields.image}}'
        field: {label: Foto, name: image, widget: image}
      - label: "Quale vino ha vinto il premio?"
        name: "wine"
        widget: "relation"
        collection: "vini"
        required: true
        valueField: "wineName"
        searchFields: ["wineName"]
        displayFields: ["wineName"] 
      - label: "Quale annata ha vinto?"
        widget: "string"
        name: "annataVicente"

  - name: "prizes"
    label: "Premi (inglese)"
    extension: en.md
    format: frontmatter
    identifier_field: prize
    slug: "{{prize}}-{{annoPremio}}"
    folder: "src/cms/prizes/en"
    create: true
    sortable_fields: ['prize', 'annoPremio']
    fields:
      - label: "Nome del premio"
        widget: "string"
        name: "prize"
      - label: "lang"
        name: "lang"
        widget: "hidden"
        default: "en"
      - label: "Anno del premio"
        widget: "string"
        name: "annoPremio"
      - label: "Descrizione"
        name: "body"
        widget: "markdown"
      - label: "Foto"
        required: false
        name: "images"
        widget: "list"
        summary: '{{fields.image}}'
        field: {label: Foto, name: image, widget: image}
      - label: "Quale vino ha vinto il premio?"
        name: "wine"
        widget: "relation"
        collection: "wines"
        required: true
        valueField: "wineName"
        searchFields: ["wineName"]
        displayFields: ["wineName"] 
      - label: "Quale annata ha vinto?"
        widget: "string"
        name: "annataVicente"
